### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by raminroohi** [astro7x/fmcw-RADAR#7]
Hi,
I use code composer studio v12.0 and import the project. When I try to build the project, I encounter a couple of errors. some of them are shown below:

![image](https://user-images.githubusercontent.com/35102385/189520829-43900c7c-bf75-4e52-8133-f2e7440bb252.png)

I am using MMWave SDK v3.6

**Comment by 0xastro** [comment]
You should build the system using `ccsv9` and mmwave-sdk `v3.1.0.02`. This is strictly important and you should install the exact dependencies as follow: 

- Code Composer Studio (CCS) version `CCSV9_2`
- mmWave software development kit (SDK) version `3.1.0.02`
- TI-RTOS Kernal SYS/BIOS version `6.73.01`
- Uniflash version `5.1.0`

**Comment by 0xastro** [comment]
let me know after testing with the same versions if the you still get the same compilation errors.

**Comment by raminroohi** [comment]
Hi,
thank you for attention. After your mention I installed all dependencies same as yours but the same errors are apeared. here is a screenshot:

![ERRROR_SCREENSHOT](https://user-images.githubusercontent.com/35102385/190965491-18a472ce-d15c-4573-8ce1-472981e0bd06.png)
